### ISSUE TITLE
Multiline comment parts are interpreted as tokens

### ISSUE THREAD

**Issue by duckboycool** [Ironfacebuster/kepler-interpreter#1]
**Describe the bug**
When using a multiline comment start or end is in a statement, the interpreter runs them as if there was a token there with that name, creating errors about it not being defined.

**To Reproduce  `Required`**
1. Use a statement that contains `!--` or `--!` not at the beginning of a statement. For example, `test is !--` or `test is !-- Comment --! Int`.

**Expected behavior  `Required`**
An unexpected EOL error instead of an undeclared variable error, or a successful execution of the statement after the end of the comment close instead of an undeclared variable error.

**Platform Information**
 - Windows 10
 - kepler v1a1.1

**Comment by Ironfacebuster** [comment]
Thanks for the report! 
This has now been fixed in a1.2.
