### ISSUE TITLE
Characters after a string literal make strings interpret incorrectly

### ISSUE THREAD

**Issue by duckboycool** [Ironfacebuster/kepler-interpreter#3]
**Describe the bug**
When writing a string literal, having any ending characters besides a quote or whitespace will result in the final character being interpreted as a quote instead of the actual second quote.

**To Reproduce  `Required`**
```
> print "String"AfterQuoteChars!
String"AfterQuoteChars
> var is String and is ""LastChar.
> print var
"LastChar
```
**Expected behavior  `Required`**
An error for an unexpected token.

**Platform Information**
 - Windows 10
 - kepler v1a1.2

**Comment by Ironfacebuster** [comment]
Fixed! The fix will be available in the next release.
